- name: Installing JRE
  tasks:
    - debug: msg="Installing JRE"
    - include: jre.yml
  when: java_jre_package_name | bool

- name: Installing JDK
  tasks:
    - debug: msg="Installing JDE"
    - include: jdk.yml
  when: java_jdk_package_name | bool