---

# Installing JRE

- name: Including JRE
  import_role:
    name: java
    tasks_from: jre
  when: java_jre_package_name is defined

# # Installing JDK

- name: Including JDK
  import_role:
    name: java
    tasks_from: jdk
  when: java_jdk_package_name is defined

# END

