- name: Installing Java
  apt:
    name: ['default-jdk']
    state: present
  become: yes

- name: Deploying nomad job
  template: src={{ item.name }}.j2 dest={{ item.path }} owner=root group=root mode=0444
  with_items:
    - { "name": nomad.service, "path": /etc/systemd/system/nomad.service }
    - { "name": server.hcl, "path": /opt/nomad/etc/server.hcl }
    - { "name": client.hcl, "path": /opt/nomad/etc/client.hcl }
  become: yes

- name: Deploying JAR
