- name: Check if Samba
  stat: path={{ item.path }}
  with_items:
    - { "name": samba, "path": /usr/sbin/smbd }
  register: samba_installed
  become: yes

- name: Installing Samba
  apt: name={{ item.item.name }} state=present
  with_items: "{{ samba_installed.results }}"
  when: item.stat.exists == false
  become: yes

- name: Rendering Samba template
  template: src={{ item.name }}.j2 dest={{ item.path }} owner=root group=root mode=0644
  with_items:
    - { "name": smb.conf, "path": /etc/samba/smb.conf }
  become: yes

- name: Restarting Samba
  ansible.builtin.systemd:
    name: smbd
    state: restarted
    enabled: yes
  become: yes


