- name: Installing dnsmasq
  apt:
    name: dnsmasq
    state: present
  become: yes

- name: Rendering templates
  template: src={{ item.name }}.j2 dest={{ item.path }} owner=root group=root mode=0644
  with_items:
    - { "name": dnsmasq.conf, "path": /etc/dnsmasq.conf}
    - { "name": hosts, "path": /etc/hosts}
  become: yes
