- name: Checking GOPATH dir
  stat:
    path: "{{ gopath }}"
  register: gopath_dir

- name: Creating GOPATH dir
  file:
    path: "{{ gopath }}"
    state: directory
  when: gopath_dir.stat.exists is false

- name: Checking Hashicorp dir
  stat:
    path: "{{ gopath }}/{{ hashicorp_path }}"
  register: hashicorp_dir

- name: Creating Hashicorp dir
  file:
    path: "{{ gopath }}/{{ hashicorp_path }}"
    state: directory
  when: hashicorp_dir.stat.exists is false

- name: Installing Git
  apk:
    name: ['go', 'git', 'make', 'gcc']
    state: present
  become: yes

- name: Check if Nomad repo is already cloned
  stat:
    path: "{{ gopath }}/{{ hashicorp_path }}/nomad"
  register: nomad_dir

- name: Cloning repo
  git:
    repo: https://github.com/hashicorp/nomad.git
    dest: "{{ gopath }}/{{ hashicorp_path }}/nomad"
    version: 149b150fb2d87766b8462346d68b72831f622047 # version 1.0.4
  when: nomad_dir.stat.exists is false

- name: Check if Nomad is already built
  stat:
    path: "{{ gopath }}/bin/nomad"
  register: nomad_built

- name: Compiling Nomad
  block:

    - name: Bootstraping Nomad
      make:
        chdir: "{{ gopath }}/{{ hashicorp_path }}/nomad"
        target: bootstrap
        params:
          NUM_THREADS: 2

    - name: Compiling dev
      make:
        chdir: "{{ gopath }}/{{ hashicorp_path }}/nomad"
        target: dev
        params:
          NUM_THREADS: 2

  when: nomad_built.stat.exists is false

- name: Test the binary
  command: "{{ gopath }}/bin/nomad -version"
  register: nomad_version

- debug: msg="{{ nomad_version.stdout }}"

- debug: msg="{{ nomad_version.stderr }}"
